# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b889e0b2c62ea9ecd8a1e1a9eff6ebbcec0b4b34e6a027f5de732f311a40f5bada70e8aaeb83ec3c9e62a52844c58b74e5fa660a81ef3af06656c9aa369e750

test:
  secret_key_base: c27ee1ea85e11ef4c7deb9acd208464b3a0cd448e8ba8a0c7259e8a6df52b459e2eeb1cfee429ce4eb31638b40d0125b76a9c4c074c719a26a085bbd18003604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
